version: "2"

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: fikasio-client
        restart: always
        environment:
            - ESLINT_NO_DEV_ERRORS=true
            - NODE_ENV=development
        ports:
            - 3000:3000
        stdin_open: true
        networks:
            - appnetwork
        volumes:
            - .:/client
            - /node_modules

    server:
        image: registry.digitalocean.com/samdouble/fikasio-api:1.0.14
        container_name: fikasio-server
        restart: always
        environment:
            - MONGO_URL=mongodb://127.0.0.1:27017/
            - NODE_ENV=development
        ports:
            - 8000:8000
        networks:
            - appnetwork

networks:
    appnetwork:
        driver: bridge
