version: "2"

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: fikasio-client
        restart: always
        environment:
            - ESLINT_NO_DEV_ERRORS=true
            - NODE_ENV=development
        ports:
            - 3000:3000
        stdin_open: true
        networks:
            - appnetwork
        volumes:
            - .:/client
            - /node_modules

    server:
        image: registry.digitalocean.com/samdouble/fikasio-api:1.0.14
        container_name: fikasio-server
        restart: always
        environment:
            - COINBASE_API_KEY=ac099394-8a7d-4d91-9552-feaa99762bca
            - COINBASE_WEBHOOK_SECRET=9ab952b6-5554-45e0-9c83-98d3afcbd060
            - HTTP_PORT=8000
            - JWT_SECRET=c581a23cbcb811eab3de0242ac130004
            - MONGO_URL=mongodb+srv://admin:HoJXkbEEb6bL8RiBqXW6xRcVV3GjDJyNb694e5ZMxsq6sCx5rjiV9V5C@clustersports.rt2re.mongodb.net/app?w=majority
            - NODE_ENV=development
            - SMTP_HOST=email-smtp.us-east-1.amazonaws.com
            - SMTP_PORT=465
            - SMTP_PASSWORD=BAAe78HyM/pfyRp0yzu2jYfUNqGLpbN0NsbepZeeqk6u
            - SMTP_USERNAME=AKIA4EDTOL4M2A3KDITK
            - STRIPE_SECRET_KEY=sk_test_51MPzjFKNaseDhZXFfRi9oJZzmKtNJlYiLgr31527b5ybUbdStNgVBCODD8mTHnIKiMwZOA0i08P9LQ8DShBGNqUE005Lq34a3K
        ports:
            - 8000:8000
        networks:
            - appnetwork

networks:
    appnetwork:
        driver: bridge
