version: "2"

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: fikasio-client
        restart: always
        env_file: .env.client
        ports:
            - 3000:3000
        stdin_open: true
        networks:
            - appnetwork
        volumes:
            - .:/client
            - /node_modules

    server:
        #image: registry.digitalocean.com/samdouble/fikasio-api:latest
        build:
            context: ../fikasio-server
            dockerfile: Dockerfile.prod
        container_name: fikasio-server
        restart: always
        env_file: .env.server
        links:
            - mongodb-init
            - mongo0
            - mongo1
            - mongo2
        ports:
            - 8000:8000
        networks:
            - appnetwork
            - dbnetwork

    mongodb-init:
        build: ./db
        links:
            - mongo0
            - mongo1
            - mongo2
        networks:
            - dbnetwork
        logging:
            driver: none

    mongo0:
        hostname: mongo0
        container_name: mongo0
        image: mongo:7.0.5
        ports:
            - 27017:27017
        expose:
            - 27017
        restart: always
        entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
        environment:
            - MONGO_INITDB_DATABASE=RD
        networks:
            - dbnetwork
        volumes:
            - ./volume-database:/data/db
        logging:
            driver: none

    mongo1:
        hostname: mongo1
        container_name: mongo1
        image: mongo:7.0.5
        ports:
            - 27018:27017
        expose:
            - 27018
        restart: always
        entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
        networks:
            - dbnetwork
        logging:
            driver: none

    mongo2:
        hostname: mongo2
        container_name: mongo2
        image: mongo:7.0.5
        ports:
            - 27019:27017
        expose:
            - 27019
        restart: always
        entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
        networks:
            - dbnetwork
        logging:
            driver: none

networks:
    appnetwork:
        driver: bridge
    dbnetwork:
        driver: bridge
