FROM node:22.9.0

ENV NODE_ENV=production

WORKDIR /app
COPY package.json yarn.lock tsconfig.json /app/
COPY public /app/public
COPY src /app/src
RUN export REACT_APP_VERSION=$(yarn -s run version) && yarn && yarn build
RUN yarn global add serve
EXPOSE 3000

CMD ["yarn", "serve"]
