version: 2.1

jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint, audit and test
          command: |
            yarn
            yarn lint
            yarn test
            yarn build
      - run:
          name: Build Docker image
          command: |
            export APP_NAME=fikasio-client
            export IMAGE_NAME=registry.digitalocean.com/samdouble/$APP_NAME
            docker build -t $IMAGE_NAME -f Dockerfile.prod .
            docker login -u $DIGITALOCEAN_API_TOKEN -p $DIGITALOCEAN_API_TOKEN registry.digitalocean.com
            docker push $IMAGE_NAME
      #- run:
      #    name: Run Playwright tests
      #    command: |
      #      cd client
      #      yarn
      #      npx playwright install
      #      npx playwright install-deps
      #      yarn add start-server-and-test
      #      npx start-server-and-test "yarn start" http://localhost:3000 "npx playwright test"
